Lifemapper Client Library: LmClient.rad.RADClient Class Reference
LmClient.rad.RADClient Class Reference
: Lifemapper RAD web service functions
Public Member Functions
def __init__ (self, cl)
: Constructor
def countExperiments (self, afterTime=None, beforeTime=None, epsgCode=None)
: Counts experiments for a user
def deleteExperiment (self, expId)
: Deletes a Lifemapper RAD experiment
def getExperiment (self, expId)
: Returns a Lifemapper RAD experiment
def getExperimentLayerIndices (self, expId, fileName)
: Returns the layer indices for an experiment as a pickle
def listExperiments (self, afterTime=None, beforeTime=None, epsgCode=None, page=0, perPage=100, fullObjects=False)
: Lists experiments for a user
def postExperiment (self, name, epsgCode, email=None, description=None)
: Posts a new Lifemapper RAD experiment
def countBuckets (self, expId, afterTime=None, beforeTime=None)
: Counts buckets for a user
def deleteBucket (self, experimentId, bucketId)
: Delete a bucket from the Lifemapper system
def getBucket (self, experimentId, bucketId)
: Get one of an experiment's buckets
def getBucketShapegridData (self, filePath, expId, bucketId, intersected=False)
: Gets a bucket's shapegrid as a shapefile
def getBucketSitesPresent (self, filePath, expId, bucketId)
: Gets the sites present for a bucket (original pamsum) as a pickle
def listBuckets (self, expId, afterTime=None, beforeTime=None, page=0, perPage=100, fullObjects=False)
: Lists buckets for a user
def addBucket (self, expId, shpName, cellShape, cellSize, mapUnits, epsgCode, bbox, cutout=None)
: Adds a bucket to an experiment
def addBucketByShapegridId (self, expId, shpId)
: Adds a bucket to an experiment
def intersectBucket (self, expId, bucketId)
: Requests that an intersection is performed against a bucket or all of the buckets in an experiment
def randomizeBucket (self, expId, bucketId, method='swap', numSwaps=10000)
: Requests that a bucket be randomized
def getOriginalPamCsv (self, experimentId, bucketId, headers=False, filePath=None)
: Get the experiment's bucket's orginal pam in CSV format
def addAncLayer (self, expId, lyrId, attrValue=None, calculateMethod="weightedMean", minPercent=None)
: Adds an ancillary layer to a RAD experiment
def getAncillaryLayer (self, expId, ancLyrId)
: Get a specific ancillary layer
def listAncillaryLayers (self, expId, afterTime=None, beforeTime=None, epsgCode=None, layerId=None, layerName=None, page=0, perPage=100, ancillaryValueId=None, fullObjects=False)
: Lists Ancillary layers for a user
def countAncillaryLayers (self, expId, afterTime=None, beforeTime=None, epsgCode=None, layerId=None, layerName=None, ancillaryValueId=None)
: Counts Ancillary layers for a user
def getAncLayers (self, expId)
: Get ancillary layers associated with an experiment
def addPALayer (self, expId, lyrId, attrPresence, minPresence, maxPresence, percentPresence, attrAbsence=None, minAbsence=None, maxAbsence=None, percentAbsence=None)
: Adds a presence / absence layer to an experiment
def getPresenceAbsenceLayer (self, expId, paLyrId)
: Get a specific presence absence layer
def listPresenceAbsenceLayers (self, expId, afterTime=None, beforeTime=None, epsgCode=None, layerId=None, layerName=None, page=0, perPage=100, presenceAbsenceId=None, fullObjects=False)
: Lists Presence Absence layers for a user
def countPresenceAbsenceLayers (self, expId, afterTime=None, beforeTime=None, epsgCode=None, layerId=None, layerName=None, presenceAbsenceId=None)
: Counts Presence Absence layers for a user
def removePALayerFromExperiment (self, expId, paLyrId)
: Removes a presence / absence layer from an experiment
def getPALayers (self, expId)
: Get presence / absence layers associated with an experiment
def addTreeForExperiment (self, expId, filename=None, jTree=None)
: Adds a json tree to an experiment
def getTreeForExperiment (self, expId, filename=None)
: Get the json tree for an experiment
def countPamSums (self, expId, bucketId, afterTime=None, beforeTime=None, randomized=1, randomMethod=None)
: Counts pamsums for a user
def deletePamSum (self, expId, bucketId, pamSumId)
: Deletes a Lifemapper RAD PAM Sum
def getPamSum (self, expId, bucketId, pamSumId)
: Returns a pamsum
def getPamSumCsv (self, expId, bucketId, pamSumId, headers=False, filePath=None)
: Returns a pamsum in CSV format
def getPamSumShapegrid (self, filePath, experimentId, bucketId, pamsumId)
: Gets the shapegrid containing pamsum data
def getPamSumStatistic (self, expId, bucketId, pamSumId, stat)
: Gets the available statistics for a pamsum
def getPamSumStatisticsKeys (self, expId, bucketId, pamSumId, keys="keys")
: Gets the available statistics for a pamsum
def listPamSums (self, expId, bucketId, afterTime=None, beforeTime=None, page=0, perPage=100, randomized=1, randomMethod=None, fullObjects=False)
: Lists pamsums for a user
def countLayers (self, afterTime=None, beforeTime=None, epsgCode=None, layerName=None)
: Counts layers for a user
def deleteLayer (self, layerId)
: Deletes a layer from Lifemapper
def getLayer (self, layerId)
: Gets a layer metadata object
def listLayers (self, afterTime=None, beforeTime=None, epsgCode=None, layerName=None, page=0, perPage=100, fullObjects=False)
: Lists layers for a user
def postRaster (self, name, filename=None, layerUrl=None, layerContent=None, epsgCode=4326, title=None, bbox=None, startDate=None, endDate=None, mapUnits="dd", resolution=None, valUnits=None, dataFormat="GTiff", valAttribute=None, description=None, keywords=[])
: Uploads a raster layer to Lifemapper to be used in experiments
def postVector (self, name, filename=None, layerUrl=None, layerContent=None, epsgCode=4326, title=None, bbox=None, startDate=None, endDate=None, mapUnits="dd", resolution=None, valUnits=None, dataFormat="ESRI Shapefile", valAttribute=None, description=None, keywords=[])
: Uploads a vector layer to Lifemapper to be used in experiments
def countShapegrids (self, afterTime=None, beforeTime=None, epsgCode=None, cellSides=None, layerId=None, layerName=None)
: Counts shapegrids for a user
def deleteShapegrid (self, shpId)
: Deletes a shapegrid from the Lifemapper system
def getShapegrid (self, shpId)
: Returns a shapegrid's metadata
def listShapegrids (self, afterTime=None, beforeTime=None, epsgCode=None, cellSides=None, layerId=None, layerName=None, page=0, perPage=100, fullObjects=False)
: Lists shapegrids for a user
def getStatusStage (self, obj)
: Gets that status and stage of an object
Public Attributes
cl
Static Public Attributes
url
obj
string method = "POST"
list parameters = [("request", "Execute")],
body = postXml,
dictionary headers = {"Content-Type" : "application/xml"},
bool objectify = True
Detailed Description
: Lifemapper RAD web service functions
Definition at line 51 of file rad.py.
Constructor & Destructor Documentation
def LmClient.rad.RADClient.__init__ (self, cl)
: Constructor
Definition at line 57 of file rad.py.
Member Function Documentation
def LmClient.rad.RADClient.addAncLayer (self, expId, lyrId, attrValue = None, calculateMethod = "weightedMean", minPercent = None)
: Adds an ancillary layer to a RAD experiment
Parameters
expId The id of the experiment to add the ancillary layer to
lyrId The id of the layer to add
attrValue (optional) The attribute value
calculateMethod (optional) The method used for calculation
minPercent (optional) The minimum percentage for presence
Note
: This service is still experimental and may not work as expected
Definition at line 539 of file rad.py.
Referenced by LmClient.rad.RADClient.getOriginalPamCsv().
def LmClient.rad.RADClient.addBucket (self, expId, shpName, cellShape, cellSize, mapUnits, epsgCode, bbox, cutout = None)
: Adds a bucket to an experiment
Parameters
expId The id of the experiment to add a bucket to
shpName The name of this new bucket's shapegrid
cellShape The shape of the cells for the shapegrid
cellSize The size of the cells in mapUnits
mapUnits The units of the cell size (ie: dd for decimal degrees)
epsgCode The EPSG code representing the projection of the bucket
bbox The bounding box for the new bucket
cutout (optional) WKT representing the area to cut out
Definition at line 298 of file rad.py.
Referenced by LmClient.rad.RADClient.listBuckets().
def LmClient.rad.RADClient.addBucketByShapegridId (self, expId, shpId)
: Adds a bucket to an experiment
Parameters
expId The id of the experiment to add a bucket to
shpId The id of the shapegrid to use for this bucket
Definition at line 357 of file rad.py.
def LmClient.rad.RADClient.addPALayer (self, expId, lyrId, attrPresence, minPresence, maxPresence, percentPresence, attrAbsence = None, minAbsence = None, maxAbsence = None, percentAbsence = None)
: Adds a presence / absence layer to an experiment
Parameters
expId The id of the experiment to add this layer for
lyrId The id of the layer to add
attrPresence The attribute indicating presence
minPresence The minimum value indicating presence
maxPresence The maximum value indicating presence
percentPresence The proportion required to indicate presence
attrAbsence (optional) The attribute indicating absence
minAbsence (optional) The minimum value indicating absence
maxAbsence (optional) The maximum value indicating absence
percentAbsence (optional) The portion required to indicate absence
Definition at line 711 of file rad.py.
Referenced by LmClient.rad.RADClient.getAncLayers().
def LmClient.rad.RADClient.addTreeForExperiment (self, expId, filename = None, jTree = None)
: Adds a json tree to an experiment
Parameters
expId The id of the experiment to add this layer for
filename (optional) The file path where the tree can be found
jTree (optional) The tree data as a string
Note
: One of filename or jTree must be supplied
Definition at line 899 of file rad.py.
def LmClient.rad.RADClient.countAncillaryLayers (self, expId, afterTime = None, beforeTime = None, epsgCode = None, layerId = None, layerName = None, ancillaryValueId = None)
: Counts Ancillary layers for a user
Parameters
expId The id of the experiment to count ancillary layers for
afterTime (optional) Count ancillary layers with creation times after this time (ISO 8601 format)
beforeTime (optional) Count ancillary layers with creation times before this time (ISO 8601 format)
epsgCode (optional) Count ancillary layers with this EPSG code
layerId (optional) Count ancillary layers that use the layer with this id
layerName (optional) Count ancillary layers with layers that have this name
ancillaryValueId (optional) Count ancillary layers that have the ancillary values specified by this id
Definition at line 660 of file rad.py.
Referenced by LmClient.rad.RADClient.listAncillaryLayers().
def LmClient.rad.RADClient.countBuckets (self, expId, afterTime = None, beforeTime = None)
: Counts buckets for a user
Parameters
expId The id of the experiment to count buckets for
afterTime (optional) Count buckets with creation times after this time (ISO 8601 format)
beforeTime (optional) Count buckets with creation times before this time (ISO 8601 format)
Definition at line 189 of file rad.py.
def LmClient.rad.RADClient.countExperiments (self, afterTime = None, beforeTime = None, epsgCode = None)
: Counts experiments for a user
Parameters
afterTime (optional) List experiments with creation times after this time (ISO 8601 format)
beforeTime (optional) List experiments with creation times before this time (ISO 8601 format)
epsgCode (optional) The epsg code of the experiments to return
Definition at line 73 of file rad.py.
def LmClient.rad.RADClient.countLayers (self, afterTime = None, beforeTime = None, epsgCode = None, layerName = None)
: Counts layers for a user
Parameters
afterTime (optional) Count layers with creation times after this time (ISO 8601 format)
beforeTime (optional) Count layers with creation times before this time (ISO 8601 format)
epsgCode (optional) Count layers with this EPSG code
layerName (optional) Count layers that match this name
Definition at line 1159 of file rad.py.
Referenced by LmClient.rad.RADClient.listPamSums().
def LmClient.rad.RADClient.countPamSums (self, expId, bucketId, afterTime = None, beforeTime = None, randomized = 1, randomMethod = None)
: Counts pamsums for a user
Parameters
expId The id of the experiment
bucketId The id of the bucket
afterTime (optional) Count pamsums with creation times after this time (ISO 8601 format)
beforeTime (optional) Count pamsums with creation times before this time (ISO 8601 format)
randomized (optional) 1 for random pamsums, 0 for original
randomMethod (optional) Return pamsums that were randomized with this method. 0-not random, 1-swap, 2-splotch
Definition at line 985 of file rad.py.
Referenced by LmClient.rad.RADClient.getTreeForExperiment().
def LmClient.rad.RADClient.countPresenceAbsenceLayers (self, expId, afterTime = None, beforeTime = None, epsgCode = None, layerId = None, layerName = None, presenceAbsenceId = None)
: Counts Presence Absence layers for a user
Parameters
expId The id of the experiment to count PA layers for
afterTime (optional) Count presence absence layers with creation times after this time (ISO 8601 format)
beforeTime (optional) Count presence absence layers with creation times before this time (ISO 8601 format)
epsgCode (optional) Count presence absence layers with this EPSG code
layerId (optional) Count presence absence layers that use the layer with this id
layerName (optional) Count presence absence layers with layers that have this name
presenceAbsenceId (optional) Count presence absence layers that have the set of presence absence values specified by this id
Definition at line 846 of file rad.py.
Referenced by LmClient.rad.RADClient.listPresenceAbsenceLayers().
def LmClient.rad.RADClient.countShapegrids (self, afterTime = None, beforeTime = None, epsgCode = None, cellSides = None, layerId = None, layerName = None)
: Counts shapegrids for a user
Parameters
afterTime (optional) Count shapegrids with creation times after this time (ISO 8601 format)
beforeTime (optional) Count shapegrids with creation times before this time (ISO 8601 format)
epsgCode (optional) The epsg code of the shapegrids to count
cellSides (optional) The number of sides for each cell of the shapegrids. Use 4 for square grids and 6 for hexagonal.
layerId (optional) Count shapegrids with this layer id
layerName (optional) Count shapegrids with this layer name
Definition at line 1398 of file rad.py.
Referenced by LmClient.rad.RADClient.postVector().
def LmClient.rad.RADClient.deleteBucket (self, experimentId, bucketId)
: Delete a bucket from the Lifemapper system
Parameters
experimentId The experiment containing the bucket
bucket The bucket to delete
Definition at line 201 of file rad.py.
def LmClient.rad.RADClient.deleteExperiment (self, expId)
: Deletes a Lifemapper RAD experiment
Parameters
expId The id of the experiment to delete
Definition at line 85 of file rad.py.
def LmClient.rad.RADClient.deleteLayer (self, layerId)
: Deletes a layer from Lifemapper
Parameters
layerId The id of the layer to delete
Definition at line 1173 of file rad.py.
def LmClient.rad.RADClient.deletePamSum (self, expId, bucketId, pamSumId)
: Deletes a Lifemapper RAD PAM Sum
Parameters
expId The id of the experiment container
bucketId The id of the bucket containing the pamsum
pamSumId The id of the pamsum to delete
Definition at line 1001 of file rad.py.
def LmClient.rad.RADClient.deleteShapegrid (self, shpId)
: Deletes a shapegrid from the Lifemapper system
Parameters
shpId The id of the shapegrid to delete
Definition at line 1413 of file rad.py.
def LmClient.rad.RADClient.getAncillaryLayer (self, expId, ancLyrId)
: Get a specific ancillary layer
Parameters
expId The experiment that the ancillary layer belongs to
ancLyrId The id of the ancillary layer
Definition at line 599 of file rad.py.
References LmClient.rad.RADClient.listAncillaryLayers().
def LmClient.rad.RADClient.getAncLayers (self, expId)
: Get ancillary layers associated with an experiment
Parameters
expId The id of the experiment to return layers for
Note
: This service is still experimental and the results may not be as expected
Definition at line 678 of file rad.py.
References LmClient.rad.RADClient.addPALayer().
def LmClient.rad.RADClient.getBucket (self, experimentId, bucketId)
: Get one of an experiment's buckets
Parameters
experimentId The experiment containing buckets
bucketId The bucket to return
Definition at line 213 of file rad.py.
Referenced by LmClient.rad.RADClient.intersectBucket(), and LmClient.rad.RADClient.randomizeBucket().
def LmClient.rad.RADClient.getBucketShapegridData (self, filePath, expId, bucketId, intersected = False)
: Gets a bucket's shapegrid as a shapefile
Parameters
filePath The path of the location to save this file
expId The experiment containing the bucket
bucketId The id of the bucket to get the shapegrid for
intersected (optional) If True, returns intersected layers in the shapefile, else returns the shapgrid itself
Definition at line 229 of file rad.py.
def LmClient.rad.RADClient.getBucketSitesPresent (self, filePath, expId, bucketId)
: Gets the sites present for a bucket (original pamsum) as a pickle
Parameters
filePath The path of the location to save this file
expId The experiment containing the bucket
bucketId The id of the bucket to get the shapegrid for
Definition at line 249 of file rad.py.
References LmClient.rad.RADClient.listBuckets().
def LmClient.rad.RADClient.getExperiment (self, expId)
: Returns a Lifemapper RAD experiment
Parameters
expId The id of the experiment to return
Definition at line 95 of file rad.py.
def LmClient.rad.RADClient.getExperimentLayerIndices (self, expId, fileName)
: Returns the layer indices for an experiment as a pickle
Parameters
expId The id of the experiment to return the indicies for
fileName The file to store the pickled data in
Definition at line 107 of file rad.py.
References LmClient.rad.RADClient.listExperiments().
def LmClient.rad.RADClient.getLayer (self, layerId)
: Gets a layer metadata object
Parameters
layerId The id of the layer to return
Definition at line 1183 of file rad.py.
References LmClient.rad.RADClient.listLayers().
def LmClient.rad.RADClient.getOriginalPamCsv (self, experimentId, bucketId, headers = False, filePath = None)
: Get the experiment's bucket's orginal pam in CSV format
Parameters
experimentId The experiment containing buckets
bucketId The bucket to return
headers (optional) Add column headers and centroids to response
filePath (optional) File location to write the original PAM CSV
Note
: Will probably change in release
Definition at line 513 of file rad.py.
References LmClient.rad.RADClient.addAncLayer().
def LmClient.rad.RADClient.getPALayers (self, expId)
: Get presence / absence layers associated with an experiment
Parameters
expId The id of the experiment to return layers for
Definition at line 874 of file rad.py.
def LmClient.rad.RADClient.getPamSum (self, expId, bucketId, pamSumId)
: Returns a pamsum
Parameters
expId The id of the experiment container
bucketId The id of the bucket containing the pamsum
pamSumId The id of the pamsum to return
Definition at line 1014 of file rad.py.
def LmClient.rad.RADClient.getPamSumCsv (self, expId, bucketId, pamSumId, headers = False, filePath = None)
: Returns a pamsum in CSV format
Note
: Jeff, this function will be something different in the release
Parameters
expId The id of the experiment container
bucketId The id of the bucket containing the pamsum
pamSumId The id of the pamsum to return
headers (optional) Add column headers and centroids to response
filePath (optional) File location to write PAM Sum CSV
Definition at line 1031 of file rad.py.
def LmClient.rad.RADClient.getPamSumShapegrid (self, filePath, experimentId, bucketId, pamsumId)
: Gets the shapegrid containing pamsum data
Parameters
filePath The local location to store the file
experimentId The id of the experiment container
bucketId The id of the bucket containing the pamsum
pamsumId The id of the pamsum to return intersected with the shapegrid
Definition at line 1053 of file rad.py.
def LmClient.rad.RADClient.getPamSumStatistic (self, expId, bucketId, pamSumId, stat)
: Gets the available statistics for a pamsum
Parameters
expId The id of the RAD experiment
bucketId The id of the RAD bucket
pamSumId The id of the pamsum to get statistics for
stat The key of the statistic to return
Definition at line 1072 of file rad.py.
def LmClient.rad.RADClient.getPamSumStatisticsKeys (self, expId, bucketId, pamSumId, keys = "keys")
: Gets the available statistics for a pamsum
Parameters
expId The id of the RAD experiment
bucketId The id of the RAD bucket
pamSumId The id of the pamsum to get statistics for
keys (optional) The type of keys to return (keys | specieskeys | siteskeys | diversitykeys)
Definition at line 1102 of file rad.py.
References LmClient.rad.RADClient.listPamSums().
def LmClient.rad.RADClient.getPresenceAbsenceLayer (self, expId, paLyrId)
: Get a specific presence absence layer
Parameters
expId The experiment that the presence absence layer belongs to
ancLyrId The id of the presence absence layer
Definition at line 781 of file rad.py.
References LmClient.rad.RADClient.listPresenceAbsenceLayers().
def LmClient.rad.RADClient.getShapegrid (self, shpId)
: Returns a shapegrid's metadata
Parameters
shpId The id of the shapegrid to return
Definition at line 1423 of file rad.py.
References LmClient.rad.RADClient.listShapegrids().
def LmClient.rad.RADClient.getStatusStage (self, obj)
: Gets that status and stage of an object
Parameters
obj The object to get the status and stage of
Returns
: status, stage
Definition at line 1473 of file rad.py.
Referenced by LmClient.rad.RADClient.intersectBucket(), and LmClient.rad.RADClient.randomizeBucket().
def LmClient.rad.RADClient.getTreeForExperiment (self, expId, filename = None)
: Get the json tree for an experiment
Parameters
expId The id of the experiment to return the tree for
filename (optional) If the file name is specified, save the file
Definition at line 959 of file rad.py.
References LmClient.rad.RADClient.countPamSums().
def LmClient.rad.RADClient.intersectBucket (self, expId, bucketId)
: Requests that an intersection is performed against a bucket or all of the buckets in an experiment
Parameters
expId The id of the experiment to perform intersections for
bucketId The id of the bucket to intersect.
Definition at line 408 of file rad.py.
References LmClient.rad.RADClient.getBucket(), and LmClient.rad.RADClient.getStatusStage().
def LmClient.rad.RADClient.listAncillaryLayers (self, expId, afterTime = None, beforeTime = None, epsgCode = None, layerId = None, layerName = None, page = 0, perPage = 100, ancillaryValueId = None, fullObjects = False)
: Lists Ancillary layers for a user
Parameters
expId The id of the experiment to list ancillary layers for
afterTime (optional) List ancillary layers with creation times after this time (ISO 8601 format)
beforeTime (optional) List ancillary layers with creation times before this time (ISO 8601 format)
epsgCode (optional) List ancillary layers with this EPSG code
layerId (optional) List ancillary layers that use the layer with this id
layerName (optional) List ancillary layers with layers that have this name
page (optional) The page of results
perPage (optional) The number of results per page
ancillaryValueId (optional) List ancillary layers that have the ancillary values specified by this id
fullObjects (optional) If True, return the full objects instead of the list objects
Definition at line 628 of file rad.py.
References LmClient.rad.RADClient.countAncillaryLayers().
Referenced by LmClient.rad.RADClient.getAncillaryLayer().
def LmClient.rad.RADClient.listBuckets (self, expId, afterTime = None, beforeTime = None, page = 0, perPage = 100, fullObjects = False)
: Lists buckets for a user
Parameters
expId The id of the experiment to list buckets for
afterTime (optional) List buckets with creation times after this time (ISO 8601 format)
beforeTime (optional) List buckets with creation times before this time (ISO 8601 format)
page (optional) The page of results
perPage (optional) The number of results per page
fullObjects (optional) If True, return the full objects instead of the list objects
Definition at line 274 of file rad.py.
References LmClient.rad.RADClient.addBucket().
Referenced by LmClient.rad.RADClient.getBucketSitesPresent().
def LmClient.rad.RADClient.listExperiments (self, afterTime = None, beforeTime = None, epsgCode = None, page = 0, perPage = 100, fullObjects = False)
: Lists experiments for a user
Parameters
afterTime (optional) List experiments with creation times after this time (ISO 8601 format)
beforeTime (optional) List experiments with creation times before this time (ISO 8601 format)
epsgCode (optional) The epsg code of the experiments to return
page (optional) The page of results
perPage (optional) The number of results per page
fullObjects (optional) If True, return the full objects instead of the list objects
Definition at line 131 of file rad.py.
Referenced by LmClient.rad.RADClient.getExperimentLayerIndices().
def LmClient.rad.RADClient.listLayers (self, afterTime = None, beforeTime = None, epsgCode = None, layerName = None, page = 0, perPage = 100, fullObjects = False)
: Lists layers for a user
Parameters
afterTime (optional) List layers with creation times after this time (ISO 8601 format)
beforeTime (optional) List layers with creation times before this time (ISO 8601 format)
epsgCode (optional) List layers with this EPSG code
layerName (optional) Return layers that match this name
page (optional) The page of results
perPage (optional) The number of results per page
fullObjects (optional) If True, return the full objects instead of the list objects
Definition at line 1204 of file rad.py.
References LmClient.rad.RADClient.postRaster().
Referenced by LmClient.rad.RADClient.getLayer().
def LmClient.rad.RADClient.listPamSums (self, expId, bucketId, afterTime = None, beforeTime = None, page = 0, perPage = 100, randomized = 1, randomMethod = None, fullObjects = False)
: Lists pamsums for a user
Parameters
expId The id of the experiment
bucketId The id of the bucket
afterTime (optional) List pamsums with creation times after this time (ISO 8601 format)
beforeTime (optional) List pamsums with creation times before this time (ISO 8601 format)
page (optional) The page of results
perPage (optional) The number of results per page
randomized (optional) 1 for random pamsums, 0 for original
randomMethod (optional) Return pamsums that were randomized with this method. 0-not random, 1-swap, 2-splotch
fullObjects (optional) If True, return the full objects instead of the list objects
Definition at line 1131 of file rad.py.
References LmClient.rad.RADClient.countLayers().
Referenced by LmClient.rad.RADClient.getPamSumStatisticsKeys().
def LmClient.rad.RADClient.listPresenceAbsenceLayers (self, expId, afterTime = None, beforeTime = None, epsgCode = None, layerId = None, layerName = None, page = 0, perPage = 100, presenceAbsenceId = None, fullObjects = False)
: Lists Presence Absence layers for a user
Parameters
expId The id of the experiment to list PA layers for
afterTime (optional) List presence absence layers with creation times after this time (ISO 8601 format)
beforeTime (optional) List presence absence layers with creation times before this time (ISO 8601 format)
epsgCode (optional) List presence absence layers with this EPSG code
layerId (optional) List presence absence layers that use the layer with this id
layerName (optional) List presence absence layers with layers that have this name
page (optional) The page of results
perPage (optional) The number of results per page
presenceAbsenceId (optional) List presence absence layers that have the set of presence absence values specified by this id
fullObjects (optional) If True, return the full objects instead of the list objects
Definition at line 812 of file rad.py.
References LmClient.rad.RADClient.countPresenceAbsenceLayers().
Referenced by LmClient.rad.RADClient.getPresenceAbsenceLayer().
def LmClient.rad.RADClient.listShapegrids (self, afterTime = None, beforeTime = None, epsgCode = None, cellSides = None, layerId = None, layerName = None, page = 0, perPage = 100, fullObjects = False)
: Lists shapegrids for a user
Parameters
afterTime (optional) List shapegrids with creation times after this time (ISO 8601 format)
beforeTime (optional) List shapegrids with creation times before this time (ISO 8601 format)
epsgCode (optional) The epsg code of the shapegrids to return
cellSides (optional) The number of sides for each cell of the shapegrids. Use 4 for square grids and 6 for hexagonal.
layerId (optional) Return shapegrids with this layer id
layerName (optional) Return shapegrids with this layer name
page (optional) The page of results
perPage (optional) The number of results per page
fullObjects (optional) If True, return the full objects instead of the list objects
Definition at line 1449 of file rad.py.
Referenced by LmClient.rad.RADClient.getShapegrid().
def LmClient.rad.RADClient.postExperiment (self, name, epsgCode, email = None, description = None)
: Posts a new Lifemapper RAD experiment
Parameters
name The name of this new experiment
epsgCode The EPSG code representing the projection used for all spatial data in this experiment
email (optional) An email address to associate with this experiment
description (optional) A description of the submitted experiment
Definition at line 151 of file rad.py.
def LmClient.rad.RADClient.postRaster (self, name, filename = None, layerUrl = None, layerContent = None, epsgCode = 4326, title = None, bbox = None, startDate = None, endDate = None, mapUnits = "dd", resolution = None, valUnits = None, dataFormat = "GTiff", valAttribute = None, description = None, keywords = [])
: Uploads a raster layer to Lifemapper to be used in experiments
Parameters
name The name of this layer
filename (optional) The local location of the raster file to upload (note that this, layerUrl, or layerContent must be specified)
layerUrl (optional) The remote location (URL) of the raster file to add to Lifemapper (note that this, filename, or layerContent must be specified)
layerContent (optional) The string representation of the raster layer to be uploaded. Note that filename, layerUrl, or layerContent must be supplied.
epsgCode (optional) The EPSG code representing the projection of this layer
title (optional) The title of this uploaded layer
bbox (optional) The bounding box for this layer
startDate (optional) The start date associated with the measurements of this layer
endDate (optional) The end date associated with the measurements of this layer
mapUnits (optional) The units associated with the size of the cells in the raster
resolution (optional) The resolution of the cells in this raster
valUnits (optional) The units associated with the values in this raster
dataFormat (optional) The format of this raster
valAttribute (optional) The attribute associated with value
description (optional) A description of this raster layer
keywords (optional) A list of keywords associated with this raster
Definition at line 1252 of file rad.py.
References LmClient.rad.RADClient.postVector().
Referenced by LmClient.rad.RADClient.listLayers().
def LmClient.rad.RADClient.postVector (self, name, filename = None, layerUrl = None, layerContent = None, epsgCode = 4326, title = None, bbox = None, startDate = None, endDate = None, mapUnits = "dd", resolution = None, valUnits = None, dataFormat = "ESRI Shapefile", valAttribute = None, description = None, keywords = [])
: Uploads a vector layer to Lifemapper to be used in experiments
Parameters
name The name of this layer
filename (optional) The local location of the vector file to upload (note that this, layerUrl, or layerContent must be specified)
layerUrl (optional) The remote location (URL) of the vector file to add to Lifemapper (note that this, filename, or layerContent must be specified)
layerContent (optional) The content of the vector layer to be posted. Please note that filename, layerUrl, or layerContent must be suppplied.
epsgCode (optional) The EPSG code representing the projection of this layer
title (optional) The title of this uploaded layer
bbox (optional) The bounding box for this layer
startDate (optional) The start date associated with the measurements of this layer
endDate (optional) The end date associated with the measurements of this layer
mapUnits (optional) The units associated with the distances of the vector layer
resolution (optional) The resolution of this vector layer
valUnits (optional) The units associated with the values in this vector
dataFormat (optional) The format of this vector
valAttribute (optional) The attribute associated with value
description (optional) A description of this vector layer
keywords (optional) A list of keywords associated with this vector
Definition at line 1329 of file rad.py.
References LmClient.rad.RADClient.countShapegrids().
Referenced by LmClient.rad.RADClient.postRaster().
def LmClient.rad.RADClient.randomizeBucket (self, expId, bucketId, method = 'swap', numSwaps = 10000)
: Requests that a bucket be randomized
Parameters
expId The id of the experiment containing the bucket to randomize
bucketId The id of the bucket to randomize
method (optional) The randomization method to use (swap | splotch | grady)
numSwaps (optional) The number of successful swaps to perform
Definition at line 453 of file rad.py.
References LmClient.rad.RADClient.getBucket(), and LmClient.rad.RADClient.getStatusStage().
def LmClient.rad.RADClient.removePALayerFromExperiment (self, expId, paLyrId)
: Removes a presence / absence layer from an experiment
Parameters
expId The id of the experiment to remove the PA layer from
paLyrId The presence / absence layer id in the experiment to remove
Definition at line 862 of file rad.py.
Member Data Documentation
LmClient.rad.RADClient.body = postXml, static
Definition at line 342 of file rad.py.
LmClient.rad.RADClient.cl
Definition at line 58 of file rad.py.
dictionary LmClient.rad.RADClient.headers = {"Content-Type" : "application/xml"}, static
Definition at line 343 of file rad.py.
string LmClient.rad.RADClient.method = "POST" static
Definition at line 340 of file rad.py.
LmClient.rad.RADClient.obj static
Definition at line 339 of file rad.py.
bool LmClient.rad.RADClient.objectify = True static
Definition at line 344 of file rad.py.
Referenced by LmClient.lmClientLib._Client.makeRequest().
list LmClient.rad.RADClient.parameters = [("request", "Execute")], static
Definition at line 341 of file rad.py.
Referenced by LmClient.sdm.Algorithm.getParameter(), LmClient.sdm.Algorithm.listParameterNames(), and LmClient.sdm.Algorithm.setParameter().
LmClient.rad.RADClient.url static
Definition at line 338 of file rad.py.
The documentation for this class was generated from the following file:
rad.py