Lifemapper Client Library: LmClient.sdm.SDMClient Class Reference
LmClient.sdm.SDMClient Class Reference
: Lifemapper SDM web service functions
Public Member Functions
def __init__ (self, cl)
: Constructor
def getAlgorithmFromCode (self, code)
: Deep copies an algorithm object and adds a value attribute to each parameter that is populated with the default value for that parameter
def countExperiments (self, afterTime=None, beforeTime=None, displayName=None, epsgCode=None, algorithmCode=None, occurrenceSetId=None, status=None, public=False)
: Counts the number of experiments that match the specified criteria.
def deleteExperiment (self, expId)
: Deletes a Lifemapper SDM experiment
def getExperiment (self, expId)
: Gets a Lifemapper experiment
def getExperimentPackage (self, expId, filename)
: Gets the package of output for a Lifemapper SDM experiment
def listExperiments (self, afterTime=None, beforeTime=None, displayName=None, epsgCode=None, perPage=100, page=0, algorithmCode=None, occurrenceSetId=None, status=None, public=False, fullObjects=False)
: Lists experiments that meet the specified criteria.
def postExperiment (self, algorithm, mdlScn, occSetId, prjScns=[], mdlMask=None, prjMask=None, email=None, name=None, description=None)
: Post a new Lifemapper experiment
def countLayers (self, afterTime=None, beforeTime=None, epsgCode=None, scenarioId=None, typeCode=None, public=False)
: Counts the number of layers that match the specified criteria.
def deleteLayer (self, lyrId)
: Deletes a Lifemapper environmental layer
def getLayer (self, lyrId)
: Gets a Lifemapper layer
def getLayerKML (self, lyrId, filename=None)
: Gets a Lifemapper layer as a kml file
def getLayerTiff (self, lyrId, filename=None)
: Gets a Lifemapper layer as a tiff file
def listLayers (self, afterTime=None, beforeTime=None, epsgCode=None, perPage=100, page=0, scenarioId=None, typeCode=None, public=False, fullObjects=False)
: Lists layers that meet the specified criteria.
def postLayer (self, name, epsgCode, envLayerType, units, dataFormat, fileName=None, layerUrl=None, layerContent=None, title=None, valUnits=None, startDate=None, endDate=None, resolution=None, keywords=[], description=None, isCategorical=False)
: Posts an environmental layer
def countOccurrenceSets (self, afterTime=None, beforeTime=None, displayName=None, epsgCode=None, minimumNumberOfPoints=None, public=False)
: Counts the number of occurrence sets that match the specified criteria.
def deleteOccurrenceSet (self, occId)
: Deletes a Lifemapper occurrence set
def getOccurrenceSet (self, occId)
: Gets a Lifemapper occurrence set
def getOccurrenceSetKML (self, occId, filename=None)
: Gets a Lifemapper occurrence set as a kml file
def getOccurrenceSetShapefile (self, occId, filename=None, overwrite=False)
: Gets a Lifemapper occurrence set as a shapefile
def listOccurrenceSets (self, afterTime=None, beforeTime=None, perPage=100, page=0, displayName=None, epsgCode=None, minimumNumberOfPoints=None, public=False, fullObjects=False)
: Lists occurrence sets that meet the specified criteria.
def postOccurrenceSet (self, displayName, fileType, fileName, epsgCode=4326)
: Post a new Lifemapper occurrence set
def countProjections (self, afterTime=None, beforeTime=None, displayName=None, epsgCode=None, algorithmCode=None, expId=None, occurrenceSetId=None, scenarioId=None, status=None, public=False)
: Counts the number of projections that match the specified criteria.
def deleteProjection (self, prjId)
: Deletes a Lifemapper SDM projection
def getProjection (self, prjId)
: Gets a Lifemapper projection
def getProjectionKML (self, prjId, filename=None)
: Gets a Lifemapper projection as a kml file
def getProjectionTiff (self, prjId, filename=None)
: Gets a Lifemapper projection as a tiff file
def getProjectionUrl (self, prjId, frmt="")
: Gets the url for returning a projection in the desired format
def listProjections (self, afterTime=None, beforeTime=None, displayName=None, epsgCode=None, perPage=100, page=0, algorithmCode=None, expId=None, occurrenceSetId=None, scenarioId=None, status=None, public=False, fullObjects=False)
: Lists projections that meet the specified criteria.
def countScenarios (self, afterTime=None, beforeTime=None, epsgCode=None, keyword=[], matchingScenario=None, public=False)
: Counts the number of scenarios that match the specified criteria.
def deleteScenario (self, scnId)
: Deletes a Lifemapper scenario
def getScenario (self, scnId)
: Gets a Lifemapper scenario
def listScenarios (self, afterTime=None, beforeTime=None, epsgCode=None, perPage=100, page=0, keyword=[], matchingScenario=None, public=False, fullObjects=False)
: Lists scenarios that meet the specified criteria.
def postScenario (self, layers, code, epsgCode, units, title=None, author=None, description=None, startDate=None, endDate=None, resolution=None, keywords=[])
: Posts a climate scenario to the Lifemapper web services
def countTypeCodes (self, afterTime=None, beforeTime=None, public=False)
: Counts the number of type codes that match the specified criteria.
def deleteTypeCode (self, tcId)
: Deletes a Lifemapper SDM type code
def getTypeCode (self, tcId)
: Gets a type code object
def listTypeCodes (self, afterTime=None, beforeTime=None, perPage=100, page=0, public=False, fullObjects=False)
: Lists type codes that meet the specified criteria.
def postTypeCode (self, code, title=None, description=None, keywords=[])
: Posts a new type code to the Lifemapper web services
def hint (self, query, maxReturned=None, serviceRoot=None)
: Queries for occurrence sets that match the partial query string
def searchArchive (self, query, maxReturned=None, serviceRoot=None)
: Queries the Lifemapper Solr index for archive data
def getShapefileFromOccurrencesHint (self, searchHit, filename, instanceName=None, overwrite=False)
: Downloads a shapefile from the occurrences hint service.
def getOgcEndpoint (self, obj)
: Returns the OGC endpoint for a Lifemapper SDM object
def validateAlgorithmParameters (self, algoParams, prjScns)
: Validates algorithm parameters for posting an experiment
Public Attributes
cl
algos
Private Member Functions
def _getAlgorithms (self)
: Gets available Lifemapper SDM algorithms
Detailed Description
: Lifemapper SDM web service functions
Definition at line 264 of file sdm.py.
Constructor & Destructor Documentation
def LmClient.sdm.SDMClient.__init__ (self, cl)
: Constructor
Parameters
cl Lifemapper client for connection to web services
Definition at line 271 of file sdm.py.
Member Function Documentation
def LmClient.sdm.SDMClient._getAlgorithms (self) private
: Gets available Lifemapper SDM algorithms
Returns
: Lifemapper algorithms
Definition at line 281 of file sdm.py.
def LmClient.sdm.SDMClient.countExperiments (self, afterTime = None, beforeTime = None, displayName = None, epsgCode = None, algorithmCode = None, occurrenceSetId = None, status = None, public = False)
: Counts the number of experiments that match the specified criteria.
Parameters
afterTime (optional) Count only experiments modified after this time. See time formats in the module documentation. [integer or string]
beforeTime (optional) Count only experiments modified before this time. See time formats in the module documentation. [integer or string]
displayName (optional) Count only experiments with this display name. [string]
epsgCode (optional) Count only experiments with this EPSG code [integer]
algorithmCode (optional) Count only experiments generated with this algorithm code. See available algorithms in the module documentation. [string]
occurrenceSetId (optional) Count only experiments generated from this occurrence set. [integer]
status (optional) Count only experiments with this model status. More information about status is available in the module documentation. [integer]
public (optional) If True, use the anonymous client if available
Returns
: The total number of experiments that match the given criteria. [integer]
Definition at line 340 of file sdm.py.
Referenced by LmClient.sdm.SDMClient.getAlgorithmFromCode().
def LmClient.sdm.SDMClient.countLayers (self, afterTime = None, beforeTime = None, epsgCode = None, scenarioId = None, typeCode = None, public = False)
: Counts the number of layers that match the specified criteria.
Parameters
afterTime (optional) Count only layers modified after this time. See time formats in the module documentation. [integer or string]
beforeTime (optional) Count only layers modified before this time. See time formats in the module documentation. [integer or string]
epsgCode (optional) Return only layers with this epsg code. [integer]
scenarioId (optional) Return only layers that belong to this scenario. [integer]
typeCode (optional) Return only layers that have this type code. [string]
public (optional) If True, use the anonymous client if available
Returns
: The total number of layers that match the given criteria. [integer]
Definition at line 550 of file sdm.py.
Referenced by LmClient.sdm.SDMClient.postExperiment().
def LmClient.sdm.SDMClient.countOccurrenceSets (self, afterTime = None, beforeTime = None, displayName = None, epsgCode = None, minimumNumberOfPoints = None, public = False)
: Counts the number of occurrence sets that match the specified criteria.
Parameters
afterTime (optional) Count only occurrence sets modified after this time. See time formats in the module documentation. [integer or string]
beforeTime (optional) Count only occurrence sets modified before this time. See time formats in the module documentation. [integer or string]
displayName (optional) Count only occurrence sets that have this display name. [string]
epsgCode (optional) Count only occurrence sets that use this EPSG code. [integer]
minimumNumberOfPoints (optional) Count only occurrence sets that have at least this many points. [integer]
public (optional) If True, use the anonymous client if available
Returns
: The total number of occurrence sets that match the given criteria. [integer]
Definition at line 778 of file sdm.py.
Referenced by LmClient.sdm.SDMClient.postLayer().
def LmClient.sdm.SDMClient.countProjections (self, afterTime = None, beforeTime = None, displayName = None, epsgCode = None, algorithmCode = None, expId = None, occurrenceSetId = None, scenarioId = None, status = None, public = False)
: Counts the number of projections that match the specified criteria.
Parameters
afterTime (optional) Count only projections modified after this time. See time formats in the module documentation. [integer or string]
beforeTime (optional) Count only projections modified before this time. See time formats in the module documentation. [integer or string]
displayName (optional) Count only projections with this display name. [string]
epsgCode (optional) Count only projections that use this EPSG code. [integer]
algorithmCode (optional) Count only projections that have this algorithm code. See available algorithms in the module documentation. [string]
expId (optional) Count only projections generated from this experiment. [integer]
occurrenceSetId (optional) Count only experiments generated from this occurrence set. [integer]
status (optional) Count only projections with this status. More information about status can be found in the module documentation. [integer]
public (optional) If True, use the anonymous client if available
Returns
: The total number of projections that match the given criteria. [integer]
Definition at line 986 of file sdm.py.
Referenced by LmClient.sdm.SDMClient.postOccurrenceSet().
def LmClient.sdm.SDMClient.countScenarios (self, afterTime = None, beforeTime = None, epsgCode = None, keyword = [], matchingScenario = None, public = False)
: Counts the number of scenarios that match the specified criteria.
Parameters
afterTime (optional) Count only scenarios modified after this time. See time formats in the module documentation. [integer or string]
beforeTime (optional) Count only scenarios modified before this time. See time formats in the module documentation. [integer or string]
epsgCode (optional) Count only scenarios that use this EPSG code. [integer]
keyword (optional) Count only scenarios that have the keywords in this list. [list of strings]
matchingScenario (optional) Count only scenarios that match this scenario. [integer]
public (optional) If True, use the anonymous client if available
Returns
: The number of scenarios that match the supplied criteria. [integer]
Definition at line 1169 of file sdm.py.
Referenced by LmClient.sdm.SDMClient.listProjections().
def LmClient.sdm.SDMClient.countTypeCodes (self, afterTime = None, beforeTime = None, public = False)
: Counts the number of type codes that match the specified criteria.
Parameters
afterTime (optional) Count only type codes modified after this time. See time formats in the module documentation. [integer or string]
beforeTime (optional) Count only type codes modified before this time. See time formats in the module documentation. [integer or string]
public (optional) If True, use the anonymous client if available
Returns
: The number of type codes that match the supplied criteria. [integer]
Definition at line 1319 of file sdm.py.
def LmClient.sdm.SDMClient.deleteExperiment (self, expId)
: Deletes a Lifemapper SDM experiment
Parameters
expId The id of the experiment to be deleted. [integer]
Definition at line 361 of file sdm.py.
def LmClient.sdm.SDMClient.deleteLayer (self, lyrId)
: Deletes a Lifemapper environmental layer
Parameters
lyrId The id of the layer to be deleted. [integer]
Definition at line 569 of file sdm.py.
def LmClient.sdm.SDMClient.deleteOccurrenceSet (self, occId)
: Deletes a Lifemapper occurrence set
Parameters
occId The id of the occurrence set to be deleted. [integer]
Definition at line 797 of file sdm.py.
def LmClient.sdm.SDMClient.deleteProjection (self, prjId)
: Deletes a Lifemapper SDM projection
Parameters
prjId The id of the projection to be deleted. [integer]
Definition at line 1009 of file sdm.py.
def LmClient.sdm.SDMClient.deleteScenario (self, scnId)
: Deletes a Lifemapper scenario
Parameters
scnId The id of the scenario to be deleted. [integer]
Definition at line 1189 of file sdm.py.
def LmClient.sdm.SDMClient.deleteTypeCode (self, tcId)
: Deletes a Lifemapper SDM type code
Parameters
tcId The id of the type code to be deleted. [integer]
Definition at line 1335 of file sdm.py.
def LmClient.sdm.SDMClient.getAlgorithmFromCode (self, code)
: Deep copies an algorithm object and adds a value attribute to each parameter that is populated with the default value for that parameter
Parameters
code The code of the algorithm to return
Definition at line 294 of file sdm.py.
References LmClient.sdm.SDMClient.algos, and LmClient.sdm.SDMClient.countExperiments().
def LmClient.sdm.SDMClient.getExperiment (self, expId)
: Gets a Lifemapper experiment
Parameters
expId The id of the experiment to be returned. [integer]
Returns
: A Lifemapper experiment [LmAttObj]
Definition at line 372 of file sdm.py.
def LmClient.sdm.SDMClient.getExperimentPackage (self, expId, filename)
: Gets the package of output for a Lifemapper SDM experiment
Parameters
expId The id of the experiment to be returned. [integer]
filename The file location to write the package to
Returns
: True if the write was successful
Definition at line 385 of file sdm.py.
References LmClient.sdm.SDMClient.listExperiments().
def LmClient.sdm.SDMClient.getLayer (self, lyrId)
: Gets a Lifemapper layer
Parameters
lyrId The id of the layer to be returned. [integer]
Returns
: A Lifemapper layer
Definition at line 580 of file sdm.py.
def LmClient.sdm.SDMClient.getLayerKML (self, lyrId, filename = None)
: Gets a Lifemapper layer as a kml file
Parameters
lyrId The id of the layer to be returned. [integer]
filename (optional) The location to save the resulting file, if None, the string is returned
Note
: This function will be removed in a later version in favor of specifying the format when making the get request Exception: Raised if write fails
Definition at line 596 of file sdm.py.
def LmClient.sdm.SDMClient.getLayerTiff (self, lyrId, filename = None)
: Gets a Lifemapper layer as a tiff file
Parameters
lyrId The id of the layer to be returned. [integer]
filename (optional) The location to save the resulting file, if None, the string is returned
Note
: This function will be removed in a later version in favor of specifying the format when making the get request Exception: Raised if write fails
Definition at line 618 of file sdm.py.
References LmClient.sdm.SDMClient.listLayers().
def LmClient.sdm.SDMClient.getOccurrenceSet (self, occId)
: Gets a Lifemapper occurrence set
Parameters
occId The id of the occurrence set to be returned. [integer]
Returns
: A Lifemapper occurrence set.
Definition at line 808 of file sdm.py.
def LmClient.sdm.SDMClient.getOccurrenceSetKML (self, occId, filename = None)
: Gets a Lifemapper occurrence set as a kml file
Parameters
occId The id of the occurrence set to get. [integer]
filename (optional) The name of the file location to save the output. [string] If it is not provided the content will be returned as a string
Note
: This function will be removed in a later version in favor of specifying the format when making the get request
Definition at line 824 of file sdm.py.
def LmClient.sdm.SDMClient.getOccurrenceSetShapefile (self, occId, filename = None, overwrite = False)
: Gets a Lifemapper occurrence set as a shapefile
Parameters
occId The id of the occurrence set to get. [integer]
filename (optional) The name of the file location to save the output. [string] If it is not provided the content will be returned as a string. If the filename is a .zip file, the output will be written to that file. If it is a .shp path, the output will use that base name for output. If the filename is a directory, the files will be written to that directory with the names in the zipfile.
overwrite (optional): Should files be overwritten if they exist?
Note
: This function will be removed in a later version in favor of specifying the format when making the get request
Definition at line 852 of file sdm.py.
References LmClient.sdm.SDMClient.listOccurrenceSets().
def LmClient.sdm.SDMClient.getOgcEndpoint (self, obj)
: Returns the OGC endpoint for a Lifemapper SDM object
Parameters
obj The object to get the OGC endpoint of
Definition at line 1515 of file sdm.py.
def LmClient.sdm.SDMClient.getProjection (self, prjId)
: Gets a Lifemapper projection
Parameters
prjId The id of the projection to be returned. [integer]
Returns
: A Lifemapper projection.
Definition at line 1020 of file sdm.py.
def LmClient.sdm.SDMClient.getProjectionKML (self, prjId, filename = None)
: Gets a Lifemapper projection as a kml file
Parameters
prjId The id of the projection to be returned. [integer]
filename (optional) The location to save the resulting file, if None, return the content of the response Exception: Raised if write fails
Note
: This function will be removed in a later version in favor of specifying the format when making the get request
Definition at line 1036 of file sdm.py.
def LmClient.sdm.SDMClient.getProjectionTiff (self, prjId, filename = None)
: Gets a Lifemapper projection as a tiff file
Parameters
prjId The id of the projection to be returned. [integer]
filename (optional) The location to save the resulting file, if None, return the content of the response Exception: Raised if write fails
Note
: This function will be removed in a later version in favor of specifying the format when making the get request
Definition at line 1058 of file sdm.py.
def LmClient.sdm.SDMClient.getProjectionUrl (self, prjId, frmt = "")
: Gets the url for returning a projection in the desired format
Parameters
prjId The projection to return
frmt (optional) The format to return the projection in
Returns
: A url pointing to the desired interface for the projection
Definition at line 1078 of file sdm.py.
References LmClient.sdm.SDMClient.listProjections().
def LmClient.sdm.SDMClient.getScenario (self, scnId)
: Gets a Lifemapper scenario
Parameters
scnId The id of the scenario to be returned. [integer]
Returns
: A Lifemapper scenario.
Definition at line 1200 of file sdm.py.
References LmClient.sdm.SDMClient.listScenarios().
def LmClient.sdm.SDMClient.getShapefileFromOccurrencesHint (self, searchHit, filename, instanceName = None, overwrite = False)
: Downloads a shapefile from the occurrences hint service.
This will start by downloading the Lifemapper shapefile but can be expanded later to query the original data source.
Parameters
searchHit The SearchHit named tuple returned by the hint service
filename The file location to save the shapefile
instanceName (optional) The name of the instance that the search hit came from. This can be used to determine how to get the data for the resuling shapefile.
overwrite (optional) Should files be overwritten if they exist?
Note
: This code should be hardened. It is mainly for the Spring 2015 iDigBio hackathon
Definition at line 1504 of file sdm.py.
Referenced by LmClient.sdm.SDMClient.searchArchive().
def LmClient.sdm.SDMClient.getTypeCode (self, tcId)
: Gets a type code object
Parameters
tcId The database id of the type code to retrieve [integer]
Returns
: A type code object
Definition at line 1346 of file sdm.py.
References LmClient.sdm.SDMClient.listTypeCodes().
def LmClient.sdm.SDMClient.hint (self, query, maxReturned = None, serviceRoot = None)
: Queries for occurrence sets that match the partial query string
Parameters
query The partial string to match (genus species). Must be at least 3 characters.
maxReturned (optional) The maximum number of results to return
serviceRoot (optional) The web server root for the hint service. Defaults to the instance that the object is connected to if None is provided.
Note
: This will return a list of SearchHit objects. These are named tuples that have the attributes: name, id, numPoints, downloadUrl and binomial. These attributes are pulled from the response from the Lucene query and may change over time.
Definition at line 1429 of file sdm.py.
def LmClient.sdm.SDMClient.listExperiments (self, afterTime = None, beforeTime = None, displayName = None, epsgCode = None, perPage = 100, page = 0, algorithmCode = None, occurrenceSetId = None, status = None, public = False, fullObjects = False)
: Lists experiments that meet the specified criteria.
Parameters
afterTime (optional) Return only experiments modified after this time. See time formats in the module documentation. [integer or string]
beforeTime (optional) Return only experiments modified before this time. See time formats in the module documentation. [integer or string]
displayName (optional) Return only experiments with this display name. [string]
epsgCode (optional) Return only experiments that use this EPSG code. [integer]
perPage (optional) Return this many results per page. [integer]
page (optional) Return this page of results. [integer]
algorithmCode (optional) Return only experiments generated from this algorithm. See available algorithms in the module documentation. [string]
occurrenceSetId (optional) Return only experiments generated from this occurrence set. [integer]
status (optional) Return only experiments with this status. More information about status can be found in the module documentation. [integer]
public (optional) If True, use the anonymous client if available
fullObjects (optional) If True, return the full objects instead of the list objects
Returns
: Experiments that match the specified parameters. [LmAttObj]
Definition at line 425 of file sdm.py.
References LmClient.sdm.SDMClient.postExperiment().
Referenced by LmClient.sdm.SDMClient.getExperimentPackage().
def LmClient.sdm.SDMClient.listLayers (self, afterTime = None, beforeTime = None, epsgCode = None, perPage = 100, page = 0, scenarioId = None, typeCode = None, public = False, fullObjects = False)
: Lists layers that meet the specified criteria.
Parameters
afterTime (optional) Return only layers modified after this time. See time formats in the module documentation. [integer or string]
beforeTime (optional) Return only layers modified before this time. See time formats in the module documentation. [integer or string]
epsgCode (optional) Return only layers with this epsg code. [integer]
perPage (optional) Return this many results per page. [integer]
page (optional) Return this page of results. [integer]
scenarioId (optional) Return only layers that belong to this scenario. [integer]
typeCode (optional) Return only layers that have this type code. [string]
public (optional) If True, use the anonymous client if available
fullObjects (optional) If True, return the full objects instead of the list objects
Returns
: Layers that match the specified parameters. [LmAttObj]
Note
: Returned object has metadata included. Reference items with "items.item" property
Definition at line 656 of file sdm.py.
References LmClient.sdm.SDMClient.postLayer().
Referenced by LmClient.sdm.SDMClient.getLayerTiff().
def LmClient.sdm.SDMClient.listOccurrenceSets (self, afterTime = None, beforeTime = None, perPage = 100, page = 0, displayName = None, epsgCode = None, minimumNumberOfPoints = None, public = False, fullObjects = False)
: Lists occurrence sets that meet the specified criteria.
Parameters
afterTime (optional) Return only occurrence sets modified after this time. See time formats in the module documentation. [integer or string]
beforeTime (optional) Return only occurrence sets modified before this time. See time formats in the module documentation. [integer or string]
epsgCode (optional) Return only occurrence sets that use this EPSG code. [integer]
perPage (optional) Return this many results per page. [integer]
page (optional) Return this page of results. [integer]
displayName (optional) Return only occurrence sets that have this display name. [string]
minimumNumberOfPoints (optional) Return only occurrence sets that have at least this many points. [integer]
public (optional) If True, use the anonymous client if available
fullObjects (optional) If True, return the full objects instead of the list objects
Returns
: Occurrence Sets that match the specified parameters. [LmAttObj]
Note
: Returned object has metadata included. Reference items with "items.item" property
Definition at line 891 of file sdm.py.
Referenced by LmClient.sdm.SDMClient.getOccurrenceSetShapefile().
def LmClient.sdm.SDMClient.listProjections (self, afterTime = None, beforeTime = None, displayName = None, epsgCode = None, perPage = 100, page = 0, algorithmCode = None, expId = None, occurrenceSetId = None, scenarioId = None, status = None, public = False, fullObjects = False)
: Lists projections that meet the specified criteria.
Parameters
afterTime (optional) Return only projections modified after this time. See time formats in the module documentation. [integer or string]
beforeTime (optional) Return only projections modified before this time. See time formats in the module documentation. [integer or string]
displayName (optional) Return only projections with this display name. [string]
epsgCode (optional) Return only projections that use this EPSG code. [integer]
perPage (optional) Return this many results per page. [integer]
page (optional) Return this page of results. [integer]
algorithmCode (optional) Return only projections that are generated from models generated from this algorithm. See available algorithms in the module documentation. [string]
expId (optional) Return only projections generated from this experiment. [integer]
occurrenceSetId (optional) Return only projections generated from models that used this occurrence set. [integer]
scenarioId (optional) Only return projections that use this scenario [integer]
status (optional) Return only projections that have this status. More information about status can be found in the module documentation. [integer]
public (optional) If True, use the anonymous client if available
fullObjects (optional) If True, return the full objects instead of the list objects
Returns
: Projections that match the specified parameters. [LmAttObj]
Note
: Returned object has metadata included. Reference items with "items.item" property
Definition at line 1123 of file sdm.py.
References LmClient.sdm.SDMClient.countScenarios().
Referenced by LmClient.sdm.SDMClient.getProjectionUrl().
def LmClient.sdm.SDMClient.listScenarios (self, afterTime = None, beforeTime = None, epsgCode = None, perPage = 100, page = 0, keyword = [], matchingScenario = None, public = False, fullObjects = False)
: Lists scenarios that meet the specified criteria.
Parameters
afterTime (optional) Return only scenarios modified after this time. See time formats in the module documentation. [integer or string]
beforeTime (optional) Return only scenarios modified before this time. See time formats in the module documentation. [integer or string]
epsgCode (optional) Return only scenarios that use this EPSG code. [integer]
perPage (optional) Return this many results per page. [integer]
page (optional) Return this page of results. [integer]
keyword (optional) Return only scenarios that have the keywords in this list. [list of strings]
matchingScenario (optional) Return only scenarios that match this scenario. [integer]
public (optional) If True, use the anonymous client if available
fullObjects (optional) If True, return the full objects instead of the list objects
Returns
: Scenarios that match the specified parameters. [LmAttObj]
Note
: Returned object has metadata included. Reference items with "items.item" property
Definition at line 1233 of file sdm.py.
References LmClient.sdm.SDMClient.postScenario().
Referenced by LmClient.sdm.SDMClient.getScenario().
def LmClient.sdm.SDMClient.listTypeCodes (self, afterTime = None, beforeTime = None, perPage = 100, page = 0, public = False, fullObjects = False)
: Lists type codes that meet the specified criteria.
Parameters
afterTime (optional) Return only type codes modified after this time. See time formats in the module documentation. [integer or string]
beforeTime (optional) Return only type codes modified before this time. See time formats in the module documentation. [integer or string]
perPage (optional) Return this many results per page. [integer]
page (optional) Return this page of results. [integer]
public (optional) If True, use the anonymous client if available
fullObjects (optional) If True, return the full objects instead of the list objects
Returns
: Type Codes that match the specified parameters. [LmAttObj]
Note
: Returned object has metadata included. Reference items with "items.item" property
Definition at line 1371 of file sdm.py.
Referenced by LmClient.sdm.SDMClient.getTypeCode().
def LmClient.sdm.SDMClient.postExperiment (self, algorithm, mdlScn, occSetId, prjScns = [], mdlMask = None, prjMask = None, email = None, name = None, description = None)
: Post a new Lifemapper experiment
Parameters
algorithm An Lifemapper SDM algorithm object
mdlScn The id of the model scenario to use for the experiment [integer]
occSetId The id of the occurrence set to be used for the experiment. [integer]
prjScns (optional) List of projection scenario ids to use for the experiment [list of integers]
mdlMask (optional) A layer id mask to use when looking at the input climate layers of the model [integer]
prjMask (optional) A layer id mask to use when projecting onto a new set of climate layers [integer]
email (optional) Lifemapper will send a notification email to this address when the experiment has completed
name (optional) A name for this experiment
description (optional) A description for this experiment
Returns
: Experiment
Definition at line 466 of file sdm.py.
References LmClient.sdm.SDMClient.countLayers(), and LmClient.sdm.SDMClient.validateAlgorithmParameters().
Referenced by LmClient.sdm.SDMClient.listExperiments().
def LmClient.sdm.SDMClient.postLayer (self, name, epsgCode, envLayerType, units, dataFormat, fileName = None, layerUrl = None, layerContent = None, title = None, valUnits = None, startDate = None, endDate = None, resolution = None, keywords = [], description = None, isCategorical = False)
: Posts an environmental layer
Parameters
name The name of the layer
epsgCode The EPSG code for the layer
envLayerType Identifier of the layer type
units The cell size units
dataFormat Indicates what format the data is in. Must be one of the formats at: http://www.gdal.org/formats_list.html
fileName (optional) The full path to the local file to be uploaded. Either fileName, layerUrl, or layerContent must be specified.
layerUrl (optional) A URL pointing to the raster file to be uploaded. Either fileName, layerUrl, or layerContent must be specified.
layerContent (optional) The layer data as a string. Either fileName, layerUrl, or layerContent must be specified.
title (optional) A longer title of the layer
valUnits (optional) The units for the values of the raster layer
startDate (optional) The start date for the layer. See time formats in module documentation
endDate (optional) The end date for the layer. See time formats in module documentation
resolution (optional) The resolution of the cells
keywords (optional) A list of keywords to associate with the layer
description (optional) A longer description of what this layer is
isCategorical (optional) Indicates if the layer contains categorical data Exception: Raised if none of layerUrl, layerContent, or filename are provided
Definition at line 710 of file sdm.py.
References LmClient.sdm.SDMClient.countOccurrenceSets().
Referenced by LmClient.sdm.SDMClient.listLayers().
def LmClient.sdm.SDMClient.postOccurrenceSet (self, displayName, fileType, fileName, epsgCode = 4326)
: Post a new Lifemapper occurrence set
Parameters
displayName The display name for the occurrence set
fileType The type of the file to upload
fileName The name of the file to upload
epsgCode (optional) The EPSG code of the occurrence data
Returns
: The occurrence set id number. [integer]
Definition at line 917 of file sdm.py.
References LmClient.sdm.SDMClient.countProjections().
def LmClient.sdm.SDMClient.postScenario (self, layers, code, epsgCode, units, title = None, author = None, description = None, startDate = None, endDate = None, resolution = None, keywords = [])
: Posts a climate scenario to the Lifemapper web services
Parameters
layers A list of layer ids that should be included in this scenario
code The code to associate with this layer
epsgCode The EPSG code representing the coordinate system projection of the scenario
units The units for the cell sizes of the scenario
title (optional) A title for this scenario
author (optional) The author of this scenario
description (optional) A longer description of what this climate scenario is and what it contains
startDate (optional) The start date for this scenario. See more information about time formats in module documentation.
endDate (optional) The end date for this scenario. See more information about time formats in module documentation
resolution (optional) The resolution of the cells
keywords (optional) A list of keywords to associate with the scenario
Definition at line 1275 of file sdm.py.
Referenced by LmClient.sdm.SDMClient.listScenarios().
def LmClient.sdm.SDMClient.postTypeCode (self, code, title = None, description = None, keywords = [])
: Posts a new type code to the Lifemapper web services
Parameters
code The code to use for this new type code [string]
title (optional) A title for this type code [string]
description (optional) An extended description of this type code [string]
keywords (optional) A list of keywords to associate with this type code [list of strings]
Returns
: An objectification of the type code that was newly created
Definition at line 1396 of file sdm.py.
def LmClient.sdm.SDMClient.searchArchive (self, query, maxReturned = None, serviceRoot = None)
: Queries the Lifemapper Solr index for archive data
Parameters
query The partial string to match (genus species).
maxReturned (optional) The maximum number of results to return
serviceRoot (optional) The web server root for the archive hint service. Defaults to the instance that the object is connected to if None is provided.
Note
: This will return all models and projections associated with occurrence sets that match this query : A list of archive hits
Definition at line 1481 of file sdm.py.
References LmClient.sdm.SDMClient.getShapefileFromOccurrencesHint().
def LmClient.sdm.SDMClient.validateAlgorithmParameters (self, algoParams, prjScns)
: Validates algorithm parameters for posting an experiment
Parameters
algoParams A list of algorithm parameter objects
prjScns A list of projection scenario ids
Note
: Throws an error if an algorithm parameter is outside of its range
: Throws an error if projections are specified and parameter dictates that they can't be
Definition at line 1531 of file sdm.py.
Referenced by LmClient.sdm.SDMClient.postExperiment().
Member Data Documentation
LmClient.sdm.SDMClient.algos
Definition at line 273 of file sdm.py.
Referenced by LmClient.sdm.SDMClient.getAlgorithmFromCode().
LmClient.sdm.SDMClient.cl
Definition at line 272 of file sdm.py.
The documentation for this class was generated from the following file:
sdm.py