Lifemapper Client Library: core.LmCommon.common.apiquery Namespace Reference
core.LmCommon.common.apiquery Namespace Reference
Classes
class APIQuery
Class to query APIs and return results.
class BisonAPI
class GbifAPI
class IdigbioAPI
class ItisAPI
Functions
def __init__ (self, qFilters={}, otherFilters={}, filterString=None, headers={'Content-Type': 'application/json'})
: Constructor for BisonAPI class
def initFromUrl (cls, url, headers={'Content-Type': 'application/json'})
def query (self)
: Queries the API and sets 'output' attribute to a JSON object
def _burrow (self, keylst)
def getTsnListForBinomials ()
: Returns a list of sequences containing tsn and tsnCount
def _getBinomialTSNs (self)
def getItisTSNValues (itisTSN)
: Return ITISScientificName, kingdom, and TSN hierarchy from one occurrence record ending in this TSN (species rank)
def getTSNOccurrences (self, asShapefile=False)
: Returns a list of dictionaries.
def getFirstValueFor (self, fieldname)
: Returns value for given fieldname in the first data record containing a value
def __init__ (self, otherFilters={})
: Constructor for ItisAPI class
def _findTaxonByRank (self, root, rankKey)
def _getRankFromPath (self, taxPath, rankKey)
def _returnHierarchy (self)
def getTaxonTSNHierarchy (self)
def __init__ (self, service=GBIF_SPECIES_SERVICE, key=None, otherFilters={})
: Constructor for GbifAPI class
def _getOutputVal (outDict, name)
def getTaxonomy (taxonKey)
: Return ITISScientificName, kingdom, and TSN hierarchy from one occurrence record ending in this TSN (species rank)
def getPublishingOrg (puborgKey)
: Return title from one organization record with this key
def initFromUrl (cls, url)
def getTaxonIdsBinomials ()
def queryByGBIFTaxonId (self, taxonKey)
: Returns a list of dictionaries.
def getOccurrences (self, asShapefile=False)
: Returns a list of dictionaries.
def testIdigbioTaxonIds (infname)
Variables
idigbio
gbif
bison
tsnList
response
loopCount
occAPI
taxAPI
tsn
count
newQ
qFilters
otherFilters = {'rows': 1})
thisurl
occList
occAPI2
occList2
tsnAPI
hier = tsnAPI.getFirstValueFor(BISON_HIERARCHY_KEY)
name = tsnAPI.getFirstValueFor(BISON_NAME_KEY)
int taxonid = 1000225
output = GbifAPI.getTaxonomy(taxonid)
string infname = '/tank/data/testcode/iDigBio/taxon_ids.txt'
idigList = testIdigbioTaxonIds(infname)
api = IdigbioAPI()
occList1 = api.queryByGBIFTaxonId(currGbifTaxonId)
url1 = api.url
Function Documentation
def core.LmCommon.common.apiquery.__init__ (self, qFilters = {}, otherFilters = {}, filterString = None, headers = {'Content-Type': 'application/json'})
: Constructor for BisonAPI class
: Constructor for IdigbioAPI class
Class to query BISON APIs and return results
Class to query iDigBio APIs and return results
Definition at line 324 of file apiquery.py.
Referenced by core.LmCommon.common.apiquery.__init__().
def core.LmCommon.common.apiquery.__init__ (self, otherFilters = {})
: Constructor for ItisAPI class
Class to query BISON APIs and return results
Definition at line 457 of file apiquery.py.
References core.LmCommon.common.apiquery.__init__().
def core.LmCommon.common.apiquery.__init__ (self, service = GBIF_SPECIES_SERVICE, key = None, otherFilters = {})
: Constructor for GbifAPI class
Class to query GBIF APIs and return results
Definition at line 522 of file apiquery.py.
References core.LmCommon.common.apiquery.__init__().
def core.LmCommon.common.apiquery._burrow (self, keylst) private
Definition at line 358 of file apiquery.py.
def core.LmCommon.common.apiquery._findTaxonByRank (self, root, rankKey) private
Definition at line 462 of file apiquery.py.
def core.LmCommon.common.apiquery._getBinomialTSNs (self) private
Definition at line 383 of file apiquery.py.
def core.LmCommon.common.apiquery._getOutputVal (outDict, name) static private
Definition at line 533 of file apiquery.py.
def core.LmCommon.common.apiquery._getRankFromPath (self, taxPath, rankKey) private
Definition at line 471 of file apiquery.py.
def core.LmCommon.common.apiquery._returnHierarchy (self) private
Note
: for
Definition at line 482 of file apiquery.py.
def core.LmCommon.common.apiquery.getFirstValueFor (self, fieldname)
: Returns value for given fieldname in the first data record containing a value
Definition at line 433 of file apiquery.py.
def core.LmCommon.common.apiquery.getItisTSNValues (itisTSN) static
: Return ITISScientificName, kingdom, and TSN hierarchy from one occurrence record ending in this TSN (species rank)
Definition at line 400 of file apiquery.py.
def core.LmCommon.common.apiquery.getOccurrences (self, asShapefile = False)
: Returns a list of dictionaries.
Each dictionary is an occurrence record
Definition at line 698 of file apiquery.py.
def core.LmCommon.common.apiquery.getPublishingOrg (puborgKey) static
: Return title from one organization record with this key
Parameters
puborgKey GBIF identifier for this publishing organization
Definition at line 597 of file apiquery.py.
References core.LmCommon.common.apiquery.query().
def core.LmCommon.common.apiquery.getTaxonIdsBinomials () static
Definition at line 666 of file apiquery.py.
def core.LmCommon.common.apiquery.getTaxonomy (taxonKey) static
: Return ITISScientificName, kingdom, and TSN hierarchy from one occurrence record ending in this TSN (species rank)
Definition at line 548 of file apiquery.py.
def core.LmCommon.common.apiquery.getTaxonTSNHierarchy (self)
Definition at line 492 of file apiquery.py.
References core.LmCommon.common.apiquery.query().
def core.LmCommon.common.apiquery.getTsnListForBinomials () static
: Returns a list of sequences containing tsn and tsnCount
Definition at line 376 of file apiquery.py.
def core.LmCommon.common.apiquery.getTSNOccurrences (self, asShapefile = False)
: Returns a list of dictionaries.
Each dictionary is an occurrence record
Definition at line 418 of file apiquery.py.
def core.LmCommon.common.apiquery.initFromUrl (cls, url, headers = {'Content-Type': 'application/json'})
Definition at line 340 of file apiquery.py.
Referenced by core.LmCommon.common.apiquery.initFromUrl().
def core.LmCommon.common.apiquery.initFromUrl (cls, url)
Definition at line 647 of file apiquery.py.
References core.LmCommon.common.apiquery.initFromUrl(), and core.LmCommon.common.apiquery.query().
def core.LmCommon.common.apiquery.query (self)
: Queries the API and sets 'output' attribute to a JSON object
: Queries the API and sets 'output' attribute to a ElementTree object
Definition at line 354 of file apiquery.py.
Referenced by core.LmCommon.common.apiquery.getPublishingOrg(), core.LmCommon.common.apiquery.getTaxonTSNHierarchy(), and core.LmCommon.common.apiquery.initFromUrl().
def core.LmCommon.common.apiquery.queryByGBIFTaxonId (self, taxonKey)
: Returns a list of dictionaries.
Each dictionary is an occurrence record
Definition at line 674 of file apiquery.py.
def core.LmCommon.common.apiquery.testIdigbioTaxonIds (infname)
Definition at line 718 of file apiquery.py.
Variable Documentation
core.LmCommon.common.apiquery.api = IdigbioAPI()
Definition at line 835 of file apiquery.py.
core.LmCommon.common.apiquery.bison
Definition at line 770 of file apiquery.py.
core.LmCommon.common.apiquery.count
Definition at line 800 of file apiquery.py.
core.LmCommon.common.apiquery.gbif
Definition at line 770 of file apiquery.py.
core.LmCommon.common.apiquery.hier = tsnAPI.getFirstValueFor(BISON_HIERARCHY_KEY)
Definition at line 816 of file apiquery.py.
core.LmCommon.common.apiquery.idigbio
Definition at line 770 of file apiquery.py.
core.LmCommon.common.apiquery.idigList = testIdigbioTaxonIds(infname)
Definition at line 828 of file apiquery.py.
string core.LmCommon.common.apiquery.infname = '/tank/data/testcode/iDigBio/taxon_ids.txt'
Definition at line 827 of file apiquery.py.
core.LmCommon.common.apiquery.loopCount
Definition at line 794 of file apiquery.py.
core.LmCommon.common.apiquery.name = tsnAPI.getFirstValueFor(BISON_NAME_KEY)
Definition at line 817 of file apiquery.py.
core.LmCommon.common.apiquery.newQ
Definition at line 802 of file apiquery.py.
core.LmCommon.common.apiquery.occAPI
Definition at line 795 of file apiquery.py.
core.LmCommon.common.apiquery.occAPI2
Definition at line 809 of file apiquery.py.
core.LmCommon.common.apiquery.occList
Definition at line 805 of file apiquery.py.
core.LmCommon.common.apiquery.occList1 = api.queryByGBIFTaxonId(currGbifTaxonId)
Definition at line 836 of file apiquery.py.
core.LmCommon.common.apiquery.occList2
Definition at line 810 of file apiquery.py.
dictionary core.LmCommon.common.apiquery.otherFilters = {'rows': 1})
Definition at line 803 of file apiquery.py.
core.LmCommon.common.apiquery.output = GbifAPI.getTaxonomy(taxonid)
Definition at line 823 of file apiquery.py.
core.LmCommon.common.apiquery.qFilters
Definition at line 803 of file apiquery.py.
core.LmCommon.common.apiquery.response
Definition at line 788 of file apiquery.py.
core.LmCommon.common.apiquery.taxAPI
Definition at line 796 of file apiquery.py.
int core.LmCommon.common.apiquery.taxonid = 1000225
Definition at line 822 of file apiquery.py.
core.LmCommon.common.apiquery.thisurl
Definition at line 804 of file apiquery.py.
core.LmCommon.common.apiquery.tsn
Definition at line 799 of file apiquery.py.
core.LmCommon.common.apiquery.tsnAPI
Definition at line 814 of file apiquery.py.
core.LmCommon.common.apiquery.tsnList
Definition at line 787 of file apiquery.py.
core.LmCommon.common.apiquery.url1 = api.url
Definition at line 837 of file apiquery.py.