Lifemapper Client Library: core.LmCommon.common.createshape Namespace Reference
core.LmCommon.common.createshape Namespace Reference
Classes
class ShapeShifter
Functions
def __init__ (self, processType, rawdata, count, logger=None, metadata=None, delimiter=')
def _createFillFeat (self, lyrDef, recDict, lyr)
def _getMetadata (self, origfldnames)
def getOgrFieldType (typeString)
def writeUserOccurrences (self, outfname, maxPoints=None, subsetfname=None)
def testShapefile (dlocation)
def writeOccurrences (self, outfname, maxPoints=None, subsetfname=None)
def _finishWrite (self, outFname, minX, maxX, minY, maxY, geomtype, fcount, subsetFname=None, subsetCount=None)
def _mapAPIResponseNames (self)
def _writeMetadata (self, basename, geomtype, count, minx, miny, maxx, maxy)
def _lookup (self, name)
def _lookupReverse (self, name)
def _getCSVReader (self, header=False)
def _getRecord (self)
def _getAPIResponseRec (self)
def _getUserCSVRec (self)
def _getCSVRec (self)
def _addUserFieldDef (self, newDataset)
def _addFieldDef (self, newDataset)
def _fillFeature (self, feat, recDict)
Variables
bool gbif = False
string outfilename = '/tmp/testpoints.shp'
string subsetOutfilename = '/tmp/testpoints_sub.shp'
basename
ext
fnames = glob.glob(basename + '*')
string testFname = '/opt/lifemapper/LmCommon/tests/data/gbif_chunk.csv'
f = open(testFname, 'r')
datachunk = f.read()
count = len(datachunk.split('\n'))
shaper = ShapeShifter(ProcessType.GBIF_TAXA_OCCURRENCE, datachunk, count)
maxPoints
subsetfname
int taxid = 2437967
occAPI = IdigbioAPI()
occList = occAPI.queryByGBIFTaxonId(taxid)
string url = 'http://bison.usgs.ornl.gov/solrproduction/occurrences/select?q=decimalLongitude%3A%5B-125+TO+-66%5D+AND+decimalLatitude%3A%5B24+TO+50%5D+AND+hierarchy_homonym_string%3A%2A-103383-%2A+NOT+basisOfRecord%3Aliving+NOT+basisOfRecord%3Afossil'
_reader
lookupFields
_currRecum
_recCount
processType
rawdata
linkField
linkUrl
computedProviderField
op
idField
xField
yField
dataFields
linkIdField
providerKeyField
_idIdx
_xIdx
_yIdx
_sortIdx
_nameIdx
fieldCount
Function Documentation
def core.LmCommon.common.createshape.__init__ (self, processType, rawdata, count, logger = None, metadata = None, delimiter = ')
Class to write a shapefile from GBIF CSV output or BISON JSON output
Parameters
data Either csv blob of GBIF data or list of dictionary records of BISON data
processType ProcessType constant, either GBIF_TAXA_OCCURRENCE, BISON_TAXA_OCCURRENCE or IDIGBIO_TAXA_OCCURRENCE
Definition at line 65 of file createshape.py.
def core.LmCommon.common.createshape._addFieldDef (self, newDataset) private
Definition at line 571 of file createshape.py.
def core.LmCommon.common.createshape._addUserFieldDef (self, newDataset) private
Definition at line 540 of file createshape.py.
def core.LmCommon.common.createshape._createFillFeat (self, lyrDef, recDict, lyr) private
Definition at line 132 of file createshape.py.
References core.LmCommon.common.unicode.fromUnicode(), and core.LmCommon.common.unicode.toUnicode().
def core.LmCommon.common.createshape._fillFeature (self, feat, recDict) private
Note
: This should return the modified feature
Definition at line 633 of file createshape.py.
References core.LmCommon.common.unicode.fromUnicode(), and core.LmCommon.common.unicode.toUnicode().
def core.LmCommon.common.createshape._finishWrite (self, outFname, minX, maxX, minY, maxY, geomtype, fcount, subsetFname = None, subsetCount = None) private
Definition at line 358 of file createshape.py.
Referenced by core.LmCommon.common.createshape.writeOccurrences().
def core.LmCommon.common.createshape._getAPIResponseRec (self) private
Note
: We modify BISON returned fieldnames, they are too long for shapefiles
Definition at line 458 of file createshape.py.
References core.LmCommon.common.unicode.fromUnicode(), and core.LmCommon.common.unicode.toUnicode().
def core.LmCommon.common.createshape._getCSVReader (self, header = False) private
Definition at line 425 of file createshape.py.
def core.LmCommon.common.createshape._getCSVRec (self) private
Definition at line 511 of file createshape.py.
References core.LmCommon.common.unicode.fromUnicode(), and core.LmCommon.common.unicode.toUnicode().
def core.LmCommon.common.createshape._getMetadata (self, origfldnames) private
Definition at line 145 of file createshape.py.
def core.LmCommon.common.createshape._getRecord (self) private
Definition at line 441 of file createshape.py.
def core.LmCommon.common.createshape._getUserCSVRec (self) private
Definition at line 482 of file createshape.py.
References core.LmCommon.common.unicode.fromUnicode(), and core.LmCommon.common.unicode.toUnicode().
def core.LmCommon.common.createshape._lookup (self, name) private
Definition at line 403 of file createshape.py.
def core.LmCommon.common.createshape._lookupReverse (self, name) private
Definition at line 414 of file createshape.py.
def core.LmCommon.common.createshape._mapAPIResponseNames (self) private
Definition at line 387 of file createshape.py.
def core.LmCommon.common.createshape._writeMetadata (self, basename, geomtype, count, minx, miny, maxx, maxy) private
Definition at line 395 of file createshape.py.
def core.LmCommon.common.createshape.getOgrFieldType (typeString) static
Definition at line 194 of file createshape.py.
def core.LmCommon.common.createshape.testShapefile (dlocation) static
Definition at line 277 of file createshape.py.
def core.LmCommon.common.createshape.writeOccurrences (self, outfname, maxPoints = None, subsetfname = None)
Definition at line 299 of file createshape.py.
References core.LmCommon.common.createshape._finishWrite(), core.LmCommon.common.unicode.fromUnicode(), and core.LmCommon.common.unicode.toUnicode().
def core.LmCommon.common.createshape.writeUserOccurrences (self, outfname, maxPoints = None, subsetfname = None)
Definition at line 210 of file createshape.py.
References core.LmCommon.common.unicode.fromUnicode(), and core.LmCommon.common.unicode.toUnicode().
Variable Documentation
core.LmCommon.common.createshape._currRecum private
Definition at line 69 of file createshape.py.
core.LmCommon.common.createshape._idIdx private
Definition at line 164 of file createshape.py.
core.LmCommon.common.createshape._nameIdx private
Definition at line 172 of file createshape.py.
core.LmCommon.common.createshape._reader private
Definition at line 66 of file createshape.py.
core.LmCommon.common.createshape._recCount private
Definition at line 70 of file createshape.py.
core.LmCommon.common.createshape._sortIdx private
Definition at line 170 of file createshape.py.
core.LmCommon.common.createshape._xIdx private
Definition at line 166 of file createshape.py.
core.LmCommon.common.createshape._yIdx private
Definition at line 168 of file createshape.py.
core.LmCommon.common.createshape.basename
Definition at line 694 of file createshape.py.
core.LmCommon.common.createshape.computedProviderField
Definition at line 75 of file createshape.py.
core.LmCommon.common.createshape.count = len(datachunk.split('\n'))
Definition at line 705 of file createshape.py.
core.LmCommon.common.createshape.datachunk = f.read()
Definition at line 702 of file createshape.py.
core.LmCommon.common.createshape.dataFields
Definition at line 93 of file createshape.py.
core.LmCommon.common.createshape.ext
Definition at line 694 of file createshape.py.
core.LmCommon.common.createshape.f = open(testFname, 'r')
Definition at line 701 of file createshape.py.
core.LmCommon.common.createshape.fieldCount
Definition at line 173 of file createshape.py.
core.LmCommon.common.createshape.fnames = glob.glob(basename + '*')
Definition at line 695 of file createshape.py.
bool core.LmCommon.common.createshape.gbif = False
Definition at line 688 of file createshape.py.
core.LmCommon.common.createshape.idField
Definition at line 88 of file createshape.py.
core.LmCommon.common.createshape.linkField
Definition at line 73 of file createshape.py.
core.LmCommon.common.createshape.linkIdField
Definition at line 97 of file createshape.py.
core.LmCommon.common.createshape.linkUrl
Definition at line 74 of file createshape.py.
core.LmCommon.common.createshape.lookupFields
Definition at line 68 of file createshape.py.
core.LmCommon.common.createshape.maxPoints
Definition at line 707 of file createshape.py.
core.LmCommon.common.createshape.occAPI = IdigbioAPI()
Definition at line 712 of file createshape.py.
core.LmCommon.common.createshape.occList = occAPI.queryByGBIFTaxonId(taxid)
Definition at line 713 of file createshape.py.
core.LmCommon.common.createshape.op
Definition at line 76 of file createshape.py.
core.LmCommon.common.createshape.outfilename = '/tmp/testpoints.shp'
Definition at line 689 of file createshape.py.
core.LmCommon.common.createshape.processType
Definition at line 71 of file createshape.py.
core.LmCommon.common.createshape.providerKeyField
Definition at line 98 of file createshape.py.
core.LmCommon.common.createshape.rawdata
Definition at line 72 of file createshape.py.
core.LmCommon.common.createshape.shaper = ShapeShifter(ProcessType.GBIF_TAXA_OCCURRENCE, datachunk, count)
Definition at line 706 of file createshape.py.
core.LmCommon.common.createshape.subsetfname
Definition at line 708 of file createshape.py.
string core.LmCommon.common.createshape.subsetOutfilename = '/tmp/testpoints_sub.shp'
Definition at line 690 of file createshape.py.
int core.LmCommon.common.createshape.taxid = 2437967
Definition at line 711 of file createshape.py.
string core.LmCommon.common.createshape.testFname = '/opt/lifemapper/LmCommon/tests/data/gbif_chunk.csv'
Definition at line 700 of file createshape.py.
string core.LmCommon.common.createshape.url = 'http://bison.usgs.ornl.gov/solrproduction/occurrences/select?q=decimalLongitude%3A%5B-125+TO+-66%5D+AND+decimalLatitude%3A%5B24+TO+50%5D+AND+hierarchy_homonym_string%3A%2A-103383-%2A+NOT+basisOfRecord%3Aliving+NOT+basisOfRecord%3Afossil'
Definition at line 722 of file createshape.py.
core.LmCommon.common.createshape.xField
Definition at line 89 of file createshape.py.
core.LmCommon.common.createshape.yField
Definition at line 90 of file createshape.py.