Lifemapper Client Library: core.LmCommon.common.verify Namespace Reference
core.LmCommon.common.verify Namespace Reference
Functions
def _getHexHashValue (dlocation=None, content=None)
: Returns a hexidecimal representation of the sha256sum of a datafile
def computeHash (dlocation=None, content=None)
: Computes an sha256sum on a datafile
def verifyHash (verify, dlocation=None, content=None)
: Computes an sha256sum on a datafile and compares it to the one sent
Function Documentation
def core.LmCommon.common.verify._getHexHashValue (dlocation = None, content = None) private
: Returns a hexidecimal representation of the sha256sum of a datafile
Parameters
dlocation The file on which to compute the hash
content The data on which to compute the hash
Note
: content is checked first, and if it exists, dlocation is ignored
Definition at line 38 of file verify.py.
Referenced by core.LmCommon.common.verify.computeHash(), and core.LmCommon.common.verify.verifyHash().
def core.LmCommon.common.verify.computeHash (dlocation = None, content = None)
: Computes an sha256sum on a datafile
Parameters
dlocation The file on which to compute the hash
Definition at line 60 of file verify.py.
References core.LmCommon.common.verify._getHexHashValue().
def core.LmCommon.common.verify.verifyHash (verify, dlocation = None, content = None)
: Computes an sha256sum on a datafile and compares it to the one sent
Parameters
dlocation The file on which to compute the hash
verify The hash to compare results
Definition at line 71 of file verify.py.
References core.LmCommon.common.verify._getHexHashValue().