Lifemapper Client Library: core.LmCommon.common.lmXml Namespace Reference
core.LmCommon.common.lmXml Namespace Reference
Classes
class Element
: Wrapper around the ElementTree Element class that also adds an optional value on construction and will fill in a default namespace if none is provided
Functions
def setDefaultNamespace (defNamespace)
: Sets the default namespace.
def CDATA (text=None)
: Adds the capability to add CDATA elements.
def SubElement (parent, tag, attrib={}, value=None, namespace=-1, extra)
: Tells the parent to create a child ElementTree Element, adds a value and a namespace to it, and then returns it
def tostring (element, encoding=None, method=None)
: ElementTree.tostring wrapper that converts an Element tree into a pretty printed string
def tostringlist (element, encoding=None, method=None)
: ElementTree.tostringlist wrapper that converts an Element tree into a pretty printed list of strings
def _serialize_xml (write, elem, encoding, qnames, namespaces)
: Monkey patch to add support for CDATA in serialization
def _processAttribs (attribDict)
: Processes attribute dictionaries to make sure keys and values are encoded correctly
def _getElemQName (namespace, tag)
: Assembles a QName object from a namespace and tag
def _prettyFormat (elem, level=0)
: Formats ElementTree element so that it prints pretty (recursive)
def _removeNSfunc (s)
def _dontRemoveNSfunc (s)
def deserialize (element, removeNS=True)
: Deserializes an ElementTree (Sub)Element into an object
def serialize (obj, parent=None)
: This function serializes an object into xml
Variables
Comment = ET.Comment
ElementPath = ET.ElementPath
ElementTree = ET.ElementTree
HTML_EMPTY = ET.HTML_EMPTY
PI = ET.PI
ParseError = ET.ParseError
ProcessingInstruction = ET.ProcessingInstruction
QName = ET.QName
TreeBuilder = ET.TreeBuilder
VERSION = ET.VERSION
XML = ET.XML
XMLID = ET.XMLID
XMLParser = ET.XMLParser
XMLTreeBuilder = ET.XMLTreeBuilder
dump = ET.dump
fromstring = ET.fromstring
fromstringlist = ET.fromstringlist
iselement = ET.iselement
iterparse = ET.iterparse
parse = ET.parse
re = ET.re
register_namespace = ET.register_namespace
sys = ET.sys
warnings = ET.warnings
__DEFAULT_NAMESPACE__ = None
Function Documentation
def core.LmCommon.common.lmXml._dontRemoveNSfunc (s) private
Definition at line 266 of file lmXml.py.
def core.LmCommon.common.lmXml._getElemQName (namespace, tag) private
: Assembles a QName object from a namespace and tag
Parameters
namespace The namespace to use for the QName
tag The tag of the QName
Note
: If namespace is -1, the default namespace (specified by DEFAULT_NAMESPACE) will be used
: If namespace is None, the QName will not have a namespace
: If tag is already a QName, it will be returned unmodified (happens for SubElements)
Definition at line 217 of file lmXml.py.
References core.LmCommon.common.lmXml.QName.
Referenced by core.LmCommon.common.lmXml.Element.__init__(), and core.LmCommon.common.lmXml.SubElement().
def core.LmCommon.common.lmXml._prettyFormat (elem, level = 0) private
: Formats ElementTree element so that it prints pretty (recursive)
Parameters
elem ElementTree element to be pretty formatted
level How many levels deep to indent for
Definition at line 238 of file lmXml.py.
Referenced by core.LmCommon.common.lmXml.tostring(), and core.LmCommon.common.lmXml.tostringlist().
def core.LmCommon.common.lmXml._processAttribs (attribDict) private
: Processes attribute dictionaries to make sure keys and values are encoded correctly
Definition at line 199 of file lmXml.py.
References core.LmCommon.common.unicode.toUnicode().
Referenced by core.LmCommon.common.lmXml.Element.__init__(), and core.LmCommon.common.lmXml.SubElement().
def core.LmCommon.common.lmXml._removeNSfunc (s) private
Definition at line 256 of file lmXml.py.
def core.LmCommon.common.lmXml._serialize_xml (write, elem, encoding, qnames, namespaces) private
: Monkey patch to add support for CDATA in serialization
Definition at line 185 of file lmXml.py.
def core.LmCommon.common.lmXml.CDATA (text = None)
: Adds the capability to add CDATA elements.
This requires a helper for serialization but will produce valid XML with CDATA
Definition at line 121 of file lmXml.py.
def core.LmCommon.common.lmXml.deserialize (element, removeNS = True)
: Deserializes an ElementTree (Sub)Element into an object
Parameters
element The element to deserialize
removeNS (optional) If true, removes the namespaces from the tags
Returns
: A new object
Definition at line 283 of file lmXml.py.
Referenced by core.LmCommon.tools.testing.testSuite.LMTestSuite.addTestsFromFile(), and LmClient.lmClientLib._Client.objectify().
def core.LmCommon.common.lmXml.serialize (obj, parent = None)
: This function serializes an object into xml
Note
: Recursive
Parameters
parent (optional) A parent element to attach this one to
Returns
: An ElementTree element representing the object : ElementTree (Sub)Element
Definition at line 356 of file lmXml.py.
References core.LmCommon.common.lmXml.SubElement().
def core.LmCommon.common.lmXml.setDefaultNamespace (defNamespace)
: Sets the default namespace.
If a namespace is not provided for an element, this one will be used
Definition at line 79 of file lmXml.py.
def core.LmCommon.common.lmXml.SubElement (parent, tag, attrib = {}, value = None, namespace = -1, extra)
: Tells the parent to create a child ElementTree Element, adds a value and a namespace to it, and then returns it
See also
: ElementTree.SubElement
Parameters
parent The parent Element
tag A tag for the element (either string or QName)
attrib (optional) A dictionary of element attributes
value (optional) The value for this element (goes in element.text)
namespace (optional) The namespace of this element
extra (optional) Extra named parameters that will be added to the element's attributes
Note
: Providing None for the namespace will result in a QName without a namespace
: Providing -1 for the namespace will result in the default namespace (DEFAULT_NAMESPACE) being used
Definition at line 144 of file lmXml.py.
References core.LmCommon.common.lmXml._getElemQName(), core.LmCommon.common.lmXml._processAttribs(), and core.LmCommon.common.unicode.toUnicode().
Referenced by core.LmCommon.common.lmXml.serialize().
def core.LmCommon.common.lmXml.tostring (element, encoding = None, method = None)
: ElementTree.tostring wrapper that converts an Element tree into a pretty printed string
See also
: ElementTree.tostring
Definition at line 158 of file lmXml.py.
References core.LmCommon.common.lmXml._prettyFormat().
def core.LmCommon.common.lmXml.tostringlist (element, encoding = None, method = None)
: ElementTree.tostringlist wrapper that converts an Element tree into a pretty printed list of strings
See also
: ElementTree.tostring
Definition at line 169 of file lmXml.py.
References core.LmCommon.common.lmXml._prettyFormat().
Variable Documentation
core.LmCommon.common.lmXml.__DEFAULT_NAMESPACE__ = None private
Definition at line 71 of file lmXml.py.
core.LmCommon.common.lmXml.Comment = ET.Comment
Definition at line 43 of file lmXml.py.
core.LmCommon.common.lmXml.dump = ET.dump
Definition at line 57 of file lmXml.py.
core.LmCommon.common.lmXml.ElementPath = ET.ElementPath
Definition at line 44 of file lmXml.py.
core.LmCommon.common.lmXml.ElementTree = ET.ElementTree
Definition at line 45 of file lmXml.py.
core.LmCommon.common.lmXml.fromstring = ET.fromstring
Definition at line 58 of file lmXml.py.
Referenced by core.LmCommon.tools.testing.testSuite.LMTestSuite.addTestsFromFile(), and LmClient.lmClientLib._Client.objectify().
core.LmCommon.common.lmXml.fromstringlist = ET.fromstringlist
Definition at line 59 of file lmXml.py.
core.LmCommon.common.lmXml.HTML_EMPTY = ET.HTML_EMPTY
Definition at line 46 of file lmXml.py.
core.LmCommon.common.lmXml.iselement = ET.iselement
Definition at line 60 of file lmXml.py.
core.LmCommon.common.lmXml.iterparse = ET.iterparse
Definition at line 61 of file lmXml.py.
core.LmCommon.common.lmXml.parse = ET.parse
Definition at line 62 of file lmXml.py.
core.LmCommon.common.lmXml.ParseError = ET.ParseError
Definition at line 48 of file lmXml.py.
core.LmCommon.common.lmXml.PI = ET.PI
Definition at line 47 of file lmXml.py.
core.LmCommon.common.lmXml.ProcessingInstruction = ET.ProcessingInstruction
Definition at line 49 of file lmXml.py.
core.LmCommon.common.lmXml.QName = ET.QName
Definition at line 50 of file lmXml.py.
Referenced by core.LmCommon.common.lmXml._getElemQName().
core.LmCommon.common.lmXml.re = ET.re
Definition at line 63 of file lmXml.py.
core.LmCommon.common.lmXml.register_namespace = ET.register_namespace
Definition at line 64 of file lmXml.py.
core.LmCommon.common.lmXml.sys = ET.sys
Definition at line 65 of file lmXml.py.
core.LmCommon.common.lmXml.TreeBuilder = ET.TreeBuilder
Definition at line 51 of file lmXml.py.
core.LmCommon.common.lmXml.VERSION = ET.VERSION
Definition at line 52 of file lmXml.py.
core.LmCommon.common.lmXml.warnings = ET.warnings
Definition at line 66 of file lmXml.py.
core.LmCommon.common.lmXml.XML = ET.XML
Definition at line 53 of file lmXml.py.
core.LmCommon.common.lmXml.XMLID = ET.XMLID
Definition at line 54 of file lmXml.py.
core.LmCommon.common.lmXml.XMLParser = ET.XMLParser
Definition at line 55 of file lmXml.py.
core.LmCommon.common.lmXml.XMLTreeBuilder = ET.XMLTreeBuilder
Definition at line 56 of file lmXml.py.